require: rubocop-rspec
AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.5.1
Rails:
    Enabled: false

Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive